# Change these first
owner: ryujishibuya # Your GitHub username
repo: website-status-by-Upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Ryuji's Site(Secret)
    url: $TEST_SITE
  - name: KOKUSAI Taro's Site(Home)
    url: https://sites.google.com/gl.aiu.ac.jp/kokusaitarostestsite/home
  - name: KOKUSAI Taro's Site(Sub1)
    url: https://sites.google.com/gl.aiu.ac.jp/kokusaitarostestsite/home/sub1
    
    
    

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /website-status-by-Upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ryuji's Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
  #  - title: Status
  #    href: https://ryujishibuya.github.io/website-status-by-Upptime
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
